server:
  port: 8080
spring:
  datasource:
    url: jdbc:mariadb://localhost:33302/schedule?autoReconnect=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

# swagger-ui custom path
#  springdoc.swagger-ui.path=/swagger-ui.html
springdoc:
  packages-to-scan: com.sparta.report.platinum
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: false