### upload banner images
POST {{host}}:{{port}}/file
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="images"; filename="retriever.png";

< retriever.png

--boundary
Content-Disposition: form-data; name="images"; filename="retriever2.png";

< retriever2.png
