version: '3'

services:
  mariadb2:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: schedule
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "33302:3306"
    volumes:
      - mariadb_data:/var/lib/mysql2

volumes:
  mariadb_data:
